[package]
name = "wstunnel-cli"
version = "10.1.11"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive", "env"] }
fdlimit = "0.3.0"
tokio = { version = "1.45.0", features = ["full"] }
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt", "local-time"] }
wstunnel = { path = ".." , features = ["clap"] }

tikv-jemallocator = {  version = "0.6", optional = true }

[features]
default = []
jemalloc = ["dep:tikv-jemallocator"]

[[bin]]
name = "wstunnel"
path = "src/main.rs"
